<?php

namespace Modules\Packages\database\seeders;

use Illuminate\Database\Seeder;
use Modules\Packages\src\Models\PackageFeature;

class PackageFeatureSeeder extends Seeder
{
    public function run(): void
    {
        $features = [
            // Group: Course Management
            [
                'key' => 'course_limit',
                'name_vi' => 'Giới hạn khóa học',
                'name_en' => 'Course Limit',
                'name_ja' => 'コース制限',
                'name_ko' => '강좌 제한',
                'name_zh' => '课程限制',
                'description_vi' => 'Số lượng khóa học tối đa bạn có thể xuất bản cùng lúc.',
                'description_en' => 'Maximum number of courses you can publish simultaneously.',
                'description_ja' => '同時に公開できるコースの最大数です。',
                'description_ko' => '동시에 게시할 수 있는 강좌의 최대 수입니다.',
                'description_zh' => '您可以同时发布的课程的最大数量。',
                'group' => 'course_management',
                'icon' => 'fas fa-book',
                'sort_order' => 1,
            ],
            [
                'key' => 'can_duplicate_courses',
                'name_vi' => 'Nhân bản khóa học',
                'name_en' => 'Duplicate Courses',
                'name_ja' => 'コースの複製',
                'name_ko' => '강좌 복제',
                'name_zh' => '复制课程',
                'description_vi' => 'Cho phép sao chép nhanh một khóa học đã có để tiết kiệm thời gian thiết lập.',
                'description_en' => 'Allows quick copying of an existing course to save setup time.',
                'description_ja' => '既存のコースを素早くコピーしてセットアップ時間を節約できます。',
                'description_ko' => '기존 강좌를 빠르게 복사하여 설정 시간을 절약할 수 있습니다.',
                'description_zh' => '允许快速复制现有课程以节省设置时间。',
                'group' => 'course_management',
                'icon' => 'fas fa-copy',
                'sort_order' => 2,
            ],
            [
                'key' => 'can_manage_quizzes',
                'name_vi' => 'Quản lý trắc nghiệm',
                'name_en' => 'Manage Quizzes',
                'name_ja' => 'クイズ管理',
                'name_ko' => '퀴즈 관리',
                'name_zh' => '管理测验',
                'description_vi' => 'Tạo và quản lý các bài kiểm tra trắc nghiệm cuối khóa để đánh giá học viên.',
                'description_en' => 'Create and manage final quiz tests for courses to evaluate students.',
                'description_ja' => '学生を評価するためのコース用最終クイズテストを作成し管理します。',
                'description_ko' => '학생들을 평가하기 위한 강좌용 최종 퀴즈 테스트를 생성하고 관리합니다.',
                'description_zh' => '为课程创建并管理最终测验测试以评估学生。',
                'group' => 'course_management',
                'icon' => 'fas fa-question-circle',
                'sort_order' => 3,
            ],
            [
                'key' => 'can_schedule_content',
                'name_vi' => 'Lịch trình bài giảng (Drip content)',
                'name_en' => 'Schedule Content (Drip)',
                'name_ja' => 'コンテンツ予約 (ドリップ)',
                'name_ko' => '콘텐츠 예약 (드립)',
                'name_zh' => '内容安排 (Drip)',
                'description_vi' => 'Mở bài học theo số ngày đăng ký hoặc trình tự nhất định (Drip Content).',
                'description_en' => 'Open lessons based on enrollment days or a specific sequence (Drip Content).',
                'description_ja' => '受講日数または特定の順序に基づいてレッスンを公開します（ドリップコンテンツ）。',
                'description_ko' => '등록일 또는 특정 순서에 따라 강의를 오픈합니다 (드립 콘텐츠).',
                'description_zh' => '根据入学天数或特定顺序开放课程（Drip 内容）。',
                'group' => 'course_management',
                'icon' => 'fas fa-calendar-alt',
                'sort_order' => 4,
            ],

            // Group: AI & Advanced Tools
            [
                'key' => 'can_use_ai_quiz',
                'name_vi' => 'Công cụ AI tạo Trắc nghiệm',
                'name_en' => 'AI Quiz Generator',
                'name_ja' => 'AIクイズジェネレーター',
                'name_ko' => 'AI 퀴즈 생성기',
                'name_zh' => 'AI 测验生成器',
                'description_vi' => 'Sử dụng trí tuệ nhân tạo để tự động tạo câu hỏi trắc nghiệm từ nội dung bài học.',
                'description_en' => 'Use artificial intelligence to automatically create quiz questions from lesson content.',
                'description_ja' => '人工知能を使用して、レッスンの内容から自動的にクイズの問題を作成します。',
                'description_ko' => '인공 지능을 사용하여 강의 콘텐츠에서 퀴즈 질문을 자동으로 생성합니다.',
                'description_zh' => '利用人工智能自动根据课程内容创建测验题目。',
                'group' => 'advanced_tools',
                'icon' => 'fas fa-robot',
                'sort_order' => 10,
            ],
            [
                'key' => 'ai_quiz_limit',
                'name_vi' => 'Giới hạn lượt dùng AI',
                'name_en' => 'AI Usage Limit',
                'name_ja' => 'AI使用制限',
                'name_ko' => 'AI 사용 제한',
                'name_zh' => 'AI 使用限制',
                'description_vi' => 'Số lượt sử dụng AI để tạo trắc nghiệm tối đa trong mỗi tháng.',
                'description_en' => 'Maximum number of AI quiz generation attempts per month.',
                'description_ja' => '1ヶ月あたりのAIクイズ生成の最大試行回数です。',
                'description_ko' => '월별 최대 AI 퀴즈 생성 시도 횟수입니다.',
                'description_zh' => '每月 AI 测验生成的最大尝试次数。',
                'group' => 'advanced_tools',
                'icon' => 'fas fa-brain',
                'sort_order' => 11,
            ],
            [
                'key' => 'can_import_export',
                'name_vi' => 'Xuất/Nhập dữ liệu Excel/CSV',
                'name_en' => 'Import/Export Excel/CSV',
                'name_ja' => 'Excel/CSVインポート/エクスポート',
                'name_ko' => 'Excel/CSV 가져오기/내보내기',
                'name_zh' => '导入/导出 Excel/CSV',
                'description_vi' => 'Quản lý dữ liệu lớn (học viên, bài giảng, kết quả) qua tệp Excel/CSV.',
                'description_en' => 'Manage large amounts of data (students, lessons, results) via Excel/CSV files.',
                'description_ja' => 'Excel/CSVファイルを介して大量のデータ（学生、レッスン、結果）を管理します。',
                'description_ko' => 'Excel/CSV 파일을 통해 대량의 데이터(학생, 강의, 결과)를 관리합니다.',
                'description_zh' => '通过 Excel/CSV 文件管理大量数据（学生、课程、结果）。',
                'group' => 'advanced_tools',
                'icon' => 'fas fa-file-excel',
                'sort_order' => 12,
            ],

            // Group: Marketing & Sales
            [
                'key' => 'can_manage_coupons',
                'name_vi' => 'Quản lý mã giảm giá',
                'name_en' => 'Manage Coupons',
                'name_ja' => 'クーポン管理',
                'name_ko' => '쿠폰 관리',
                'name_zh' => '管理优惠券',
                'description_vi' => 'Tạo các mã giảm giá riêng (chiết khấu %, giảm giá cố định) cho khóa học của bạn.',
                'description_en' => 'Create your own discount codes (percentage, fixed amount) for your courses.',
                'description_ja' => 'コース独自の割引コード（パーセンテージ、固定額）を作成します。',
                'description_ko' => '강좌를 위한 고유한 할인 코드(퍼센트, 고정 금액)를 생성합니다.',
                'description_zh' => '为您的课程创建自己的折扣代码（百分比、固定金额）。',
                'group' => 'marketing',
                'icon' => 'fas fa-ticket-alt',
                'sort_order' => 20,
            ],
            [
                'key' => 'coupon_limit',
                'name_vi' => 'Giới hạn mã giảm giá',
                'name_en' => 'Coupon Limit',
                'name_ja' => 'クーポン制限',
                'name_ko' => '쿠폰 제한',
                'name_zh' => '优惠券限制',
                'description_vi' => 'Số lượng mã giảm giá tối đa bạn có thể tạo.',
                'description_en' => 'Maximum number of coupons that can be created.',
                'description_ja' => '作成できるクーポンの最大数です。',
                'description_ko' => '생성할 수 있는 쿠폰의 최대 수입니다.',
                'description_zh' => '可以创建的优惠券的最大数量。',
                'group' => 'marketing',
                'icon' => 'fas fa-tags',
                'sort_order' => 21,
            ],
            [
                'key' => 'can_sell_bundles',
                'name_vi' => 'Bán theo Combo (Bundles)',
                'name_en' => 'Sell Bundles',
                'name_ja' => 'バンドル販売',
                'name_ko' => '번들 판매',
                'name_zh' => '捆绑销售',
                'description_vi' => 'Đóng gói nhiều khóa học liên quan để bán chung một giá ưu đãi.',
                'description_en' => 'Package multiple related courses together for a single promotional price.',
                'description_ja' => '関連する複数のコースをまとめて1つのプロモーション価格で販売します。',
                'description_ko' => '여러 관련 강좌를 하나로 묶어 단일 프로모션 가격으로 판매합니다.',
                'description_zh' => '将多个相关课程打包以单一促销价格销售。',
                'group' => 'marketing',
                'icon' => 'fas fa-layer-group',
                'sort_order' => 22,
            ],
            [
                'key' => 'can_send_promotions',
                'name_vi' => 'Thông báo quảng bá',
                'name_en' => 'Promotional Announcements',
                'name_ja' => 'プロモーション通知',
                'name_ko' => '프로모션 알림',
                'name_zh' => '推广公告',
                'description_vi' => 'Gửi thông báo đẩy hoặc email đồng loạt cho toàn bộ học viên trong hệ thống.',
                'description_en' => 'Send simultaneous push notifications or emails to all students in the system.',
                'description_ja' => 'システム内の全学生にプッシュ通知やメールを同時に送信します。',
                'description_ko' => '시스템의 모든 학생들에게 푸시 알림 또는 이메일을 동시에 보냅니다.',
                'description_zh' => '同时向系统中的所有学生发送推送通知或电子邮件。',
                'group' => 'marketing',
                'icon' => 'fas fa-bullhorn',
                'sort_order' => 23,
            ],
            [
                'key' => 'can_use_affiliate_links',
                'name_vi' => 'Tiếp thị liên kết (Affiliate)',
                'name_en' => 'Affiliate Links',
                'name_ja' => 'アフィリエイトリンク',
                'name_ko' => '제휴 링크',
                'name_zh' => '联盟链接',
                'description_vi' => 'Tạo link giới thiệu khóa học để người khác quảng bá và nhận hoa hồng.',
                'description_en' => 'Create referral links for your courses so others can promote them and earn commissions.',
                'description_ja' => '他の人がコースを宣伝して手数料を獲得できるように、コースの紹介リンクを作成します。',
                'description_ko' => '다른 사람들이 강좌를 홍보하고 수수료를 받을 수 있도록 강좌용 추천 링크를 생성합니다.',
                'description_zh' => '为您的课程创建推荐链接，以便他人推广并赚取佣金。',
                'group' => 'marketing',
                'icon' => 'fas fa-share-alt',
                'sort_order' => 24,
            ],

            // Group: Student Care & Brand
            [
                'key' => 'can_manage_students',
                'name_vi' => 'Quản lý học viên',
                'name_en' => 'Manage Students',
                'name_ja' => '学生管理',
                'name_ko' => '학생 관리',
                'name_zh' => '管理学生',
                'description_vi' => 'Xem danh sách học viên chi tiết và liên hệ trực tiếp với học viên.',
                'description_en' => 'View detailed student lists and contact students directly.',
                'description_ja' => '詳細な学生リストを閲覧し、学生に直接連絡を取ります。',
                'description_ko' => '상세 학생 목록을 확인하고 학생들과 직접 소통합니다.',
                'description_zh' => '查看详细的学生列表并直接联系学生。',
                'group' => 'student_care',
                'icon' => 'fas fa-users',
                'sort_order' => 30,
            ],
            [
                'key' => 'can_view_student_progress',
                'name_vi' => 'Theo dõi tiến độ học tập',
                'name_en' => 'Track Student Progress',
                'name_ja' => '学生の進捗追跡',
                'name_ko' => '학생 진도 추적',
                'name_zh' => '跟踪学生进度',
                'description_vi' => 'Xem chi tiết quá trình hoàn thành từng bài học của mỗi học viên.',
                'description_en' => 'View detailed completion status for each lesson for every student.',
                'description_ja' => '全学生の各レッスンの詳細な完了状況を確認します。',
                'description_ko' => '모든 학생의 각 강의별 상세 완료 현황을 확인합니다.',
                'description_zh' => '查看每位学生每节课的详细完成状态。',
                'group' => 'student_care',
                'icon' => 'fas fa-chart-line',
                'sort_order' => 31,
            ],
            [
                'key' => 'can_manage_comments',
                'name_vi' => 'Quản lý bình luận & Thảo luận',
                'name_en' => 'Manage Comments & Discussions',
                'name_ja' => 'コメントとディスカッションの管理',
                'name_ko' => '댓글 및 토론 관리',
                'name_zh' => '管理评论与讨论',
                'description_vi' => 'Phản hồi và kiểm duyệt các bình luận, câu hỏi của học viên trong bài học.',
                'description_en' => 'Reply to and moderate student comments and questions within lessons.',
                'description_ja' => 'レッスン内の学生のコメントや質問に返信し、モデレートします。',
                'description_ko' => '강의 내 학생들의 댓글과 질문에 답글을 달고 관리합니다.',
                'description_zh' => '回复并审核课程内学生的评论和提问。',
                'group' => 'student_care',
                'icon' => 'fas fa-comments',
                'sort_order' => 32,
            ],
            [
                'key' => 'can_issue_certificates',
                'name_vi' => 'Cấp Chứng chỉ hoàn thành',
                'name_en' => 'Issue Certificates',
                'name_ja' => '修了証の発行',
                'name_ko' => '수료증 발급',
                'name_zh' => '颁发证书',
                'description_vi' => 'Tự thiết kế và cấp chứng chỉ số cho học viên sau khi hoàn thành khóa học.',
                'description_en' => 'Design and issue digital certificates to students after they complete a course.',
                'description_ja' => 'コース修了後に学生にデジタル修了証をデザインし発行します。',
                'description_ko' => '강좌 수료 후 학생들에게 디지털 수료증을 디자인하고 발급합니다.',
                'description_zh' => '在学生完成课程后设计并为其颁发电子证书。',
                'group' => 'student_care',
                'icon' => 'fas fa-certificate',
                'sort_order' => 33,
            ],
            [
                'key' => 'can_verify_certificates',
                'name_vi' => 'Xác thực chứng chỉ qua QR Code',
                'name_en' => 'Certificate Verification (QR)',
                'name_ja' => 'QRコードによる修了証検証',
                'name_ko' => 'QR 코드를 통한 수료증 확인',
                'name_zh' => '证书验证 (二维码)',
                'description_vi' => 'Hệ thống hỗ trợ trang xác thực chứng chỉ thật/giả qua mã QR công khai.',
                'description_en' => 'System supports certificate authentication through public QR codes.',
                'description_ja' => '公開QRコードを介して修了証の認証をサポートします。',
                'description_ko' => '공개 QR 코드를 통해 수료증 인증을 지원합니다.',
                'description_zh' => '系统支持通过公开二维码进行证书身份验证。',
                'group' => 'student_care',
                'icon' => 'fas fa-qrcode',
                'sort_order' => 34,
            ],
            [
                'key' => 'can_customize_teacher_landing',
                'name_vi' => 'Tùy chỉnh Trang cá nhân (Landing page)',
                'name_en' => 'Customize Teacher Landing',
                'name_ja' => '講師ランディングページのカスタマイズ',
                'name_ko' => '강사 랜딩 페이지 사용자 정의',
                'name_zh' => '自定义讲师登录页',
                'description_vi' => 'Cho phép thay đổi giao diện trang giới thiệu giảng viên theo phong cách riêng.',
                'description_en' => 'Allows customizing the teacher introduction page layout and style.',
                'description_ja' => '講師紹介ページのレイアウトとスタイルをカスタマイズできます。',
                'description_ko' => '강사 소개 페이지의 레이아웃과 스타일을 사용자 정의할 수 있습니다.',
                'description_zh' => '允许自定义讲师介绍页面的布局和样式。',
                'group' => 'branding',
                'icon' => 'fas fa-paint-brush',
                'sort_order' => 40,
            ],

            // Group: Finance & System
            [
                'key' => 'commission_rate',
                'name_vi' => 'Tỉ lệ hoa hồng ưu đãi',
                'name_en' => 'Commission Rate',
                'name_ja' => '販売手数料率',
                'name_ko' => '수수료율',
                'name_zh' => '佣金比例',
                'description_vi' => 'Tỉ lệ doanh thu bạn nhận được sau khi trừ phí nền tảng.',
                'description_en' => 'The percentage of revenue you receive after platform fees.',
                'description_ja' => 'プラットフォーム手数料差し引き後に受け取る収益の割合です。',
                'description_ko' => '플랫폼 수수료를 제외하고 귀하가 받는 수익의 백분율입니다.',
                'description_zh' => '扣除平台费用后您收到的收入百分比。',
                'group' => 'finance',
                'icon' => 'fas fa-percentage',
                'sort_order' => 50,
            ],
            [
                'key' => 'payout_account_limit',
                'name_vi' => 'Giới hạn Tài khoản nhận tiền',
                'name_en' => 'Payout Account Limit',
                'name_ja' => '振込口座制限',
                'name_ko' => '출금 계좌 한도',
                'name_zh' => '提现账户限制',
                'description_vi' => 'Số lượng tài khoản ngân hàng/ví điện tử bạn có thể liên kết để nhận thanh toán.',
                'description_en' => 'Number of bank accounts or e-wallets you can link to receive payments.',
                'description_ja' => '支払いを受け取るために連携できる銀行口座または電子マネーの数です。',
                'description_ko' => '지급을 받기 위해 연결할 수 있는 은행 계좌 또는 전자 지갑의 수입니다.',
                'description_zh' => '您可以关联以接收付款的银行账户或电子钱包的数量。',
                'group' => 'finance',
                'icon' => 'fas fa-wallet',
                'sort_order' => 51,
            ],
            [
                'key' => 'max_payout_per_day',
                'name_vi' => 'Hạn mức rút tiền tối đa',
                'name_en' => 'Maximum Payout Limit',
                'name_ja' => '最大出金制限',
                'name_ko' => '최대 출금 한도',
                'name_zh' => '最高提现限制',
                'description_vi' => 'Hạn mức số tiền tối đa bạn có thể rút trong vòng 24 giờ qua.',
                'description_en' => 'The maximum amount you can withdraw within the last 24 hours.',
                'description_ja' => '過去24時間以内に引き出すことができる最大額です。',
                'description_ko' => '지난 24시간 이내에 출금할 수 있는 최대 금액입니다.',
                'description_zh' => '过去 24 小时内您可以提现的最大金额。',
                'group' => 'finance',
                'icon' => 'fas fa-money-bill-wave',
                'sort_order' => 52,
            ],
            [
                'key' => 'can_view_activity_logs',
                'name_vi' => 'Nhật ký hoạt động hệ thống',
                'name_en' => 'System Activity Logs',
                'name_ja' => 'システム操作ログ',
                'name_ko' => '시스템 활동 로그',
                'name_zh' => '系统操作日志',
                'description_vi' => 'Xem chi tiết các thay đổi cấu hình và bảo mật trên tài khoản của bạn.',
                'description_en' => 'View detailed configuration and security changes on your account.',
                'description_ja' => 'アカウントの詳細な設定変更やセキュリティの変更を確認します。',
                'description_ko' => '계정의 상세 설정 및 보안 변경 사항을 확인합니다.',
                'description_zh' => '查看您账户上的详细配置和安全更改。',
                'group' => 'system',
                'icon' => 'fas fa-history',
                'sort_order' => 60,
            ],
        ];

        foreach ($features as $feature) {
            PackageFeature::query()->updateOrCreate(
                ['key' => $feature['key']],
                $feature
            );
        }
    }
}
