import "./bootstrap.bundle.min.js"; 
// import "./bootstrap.min.js";
// import "./bootstrap.min.js.map";
import "./jquery.min.js";
import "./jquery-migrate-1.2.1.min.js";
import "./slick.min.js";
import "./slider-home.js";
import "./accordion.js";
import "./home.js";
import "./tab.js";
import "./video.min.js";
import "./account.js";
import "./checkout.js";
